config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "tasks#index"
  resources :tasks
  resources :projects
  post "tasks/:id/toggle", to: "tasks#toggle"
  post "projects/:id/toggle", to: "projects#toggle"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks
	belongs_to :creator, class_name: "User", foreign_key: "creator_id"
	validates :name, presence: true
	has_rich_text :description
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project, optional: true
	belongs_to :creator, class_name: "User", foreign_key: "creator_id"
	validates :name, presence: true
	has_rich_text :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, foreign_key: "creator_id"
  has_many :projects, foreign_key: "creator_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :projects
	before_action :authenticate_user!
	before_action :project, except: %i[new create index]

	def index
		@project = Project.new
	end

	def show; end

	def new
		@project = Project.new(project_params)
	end

	def create
		@project = current_user.projects.new(project_params)

		if @project.save
			flash.now[:notice] = "Project successfully created!"
		else
			flash.now[:notice] = "Project couldn't be created!"
		end
	end

  def update
		respond_to do |format|
			if project.update(project_params)
				format.html { redirect_to projects_url, notice: "Project was successfully updated" }
				format.turbo_stream do
					flash.now[:notice] = "Project was successfully updated!"
				end
			else
				format.html { render :edit, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		 project.destroy
		 redirect_to projects_url, notice: "Project was successfully deleted"
	end

	def toggle
		@project = Project.find(params[:id])
		if @project.update(completed: params[:completed])
			render json: {
				status: "Success",
				message: "Project Successfully Updated" 
			}
		else
			render json: {
				status: "Failure",
				message: "Project Couldn't Be Updated!" 
			}
		end
	end

	private

	def project_params
		params.require(:project).permit(:name, :description, :start_date, :end_date, :due_date)
	end

	def projects
		@projects ||= Project.all
	end

	def project
		@project ||= Project.find_by_id(params[:id])
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	helper_method :tasks
	before_action :authenticate_user!
	before_action :task, except: %i[new create index]

	def index
		@task = Task.new
	end

	def show; end

	def new
		@task = Task.new
	end

	def create
		@task = current_user.tasks.new(task_params)

		if @task.save
			redirect_to tasks_url, notice: "Task was successfully created!"	
		else
			redirect_to tasks_url, notice: @task.errors.full_messages
		end
	end

	def update
		respond_to do |format|
			if task.update(task_params)
				format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
				format.turbo_stream do
					flash.now[:notice] = "Task was successfully updated!"
				end
			else
				format.html { render :edit, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		 task.destroy
		 redirect_to tasks_url, notice: "Task was successfully deleted"
	end

	def toggle
		@task = Task.find(params[:id])
		
		respond_to do |format|
			format.json do
				if @task.update(completed: params[:completed])
					render json: {
						status: "Success",
						message: "Task Successfully Updated" 
					}
				else
					render json: {
						status: "Failure",
						message: "Task Couldn't Be Updated!" 
					}
				end
			end
			format.turbo_stream do
				flash.now[:notice] = "Task was updated!"
				turbo_stream.replace "notice", partial: "shared/flash"
			end
		end
	end

	private

	def task_params
		params.require(:task).permit(:name, :description)
	end

	def tasks
		@tasks ||= Task.all
	end

	def task
		@task ||= Task.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&family=Poppins:wght@300;400;500;700&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
      <div class="flex justify-around bg-gray-100 w-full shadow-md items-center mb-4">
        <div>
        <%= link_to tasks_path do %>
          <h1 class="text-2xl xl:text-4xl p-4 font-bold text-denim-900">campy <i class="fa-solid fa-campground"></i></h1>
        <% end %>
        </div>
        <div class="mx-8 flex font-bold text-denim-900">
          <%= link_to "tasks", tasks_path, class: "mx-2 border-b-4 border-gray-100 hover:border-denim-800 hover:text-denim-800" %>
          <%= link_to "projects", projects_path, class: "mx-2 border-b-4 border-gray-100 hover:border-denim-800 hover:text-denim-800" %>
          <% if user_signed_in? %>
            <%= button_to "logout", destroy_user_session_path, method: :delete, class: "ml-4 mr-2 border-b-4 border-gray-100 hover:border-denim-600 text-denim-600" %>
          <% end %>
        </div>
      </div>

      <%= render partial: "shared/flash" %>

      <div class="p-4">
        <%= render 'shared/toast' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= turbo_frame_tag "#{dom_id(@project)}-form" do %>
	<%= form_with(model: @project, class: "flex w-full", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |form| %>
		<div class="w-full flex flex-wrap items-center justify-center">
			<div class="flex flex-wrap items-start justify-center">
				<%= form.text_field :name, placeholder: "Project name", class: "w-full inline-block px-3 py-2 shadow rounded-md border border-gray-200 outline-none mx-1 my-1 mb-4", data: { "reset-form-target": "required" } %>
				<%= form.rich_text_area :description, placeholder: "Project description", class: "bg-white w-full inline-block px-3 py-2 shadow rounded-md border border-gray-200 outline-none mx-1 my-1", data: { "reset-form-target": "required" } %>
			</div>
			<div class="flex flex-wrap w-full justify-center items-center my-3">
			<%= form.label "start date", class: "mr-1 text-gray-500" %>
			<%= form.date_field :start_date, class: "w-full md:w-auto px-3 py-2 shadow rounded-md border border-gray-200 outline-none mx-1" %>
			<%= form.label "end date", class: "mr-1 text-gray-500" %>
			<%= form.date_field :end_date, class: "w-full md:w-auto px-3 py-2 shadow rounded-md border border-gray-200 outline-none mx-1" %>
			<%= form.label "due date", class: "mr-1 text-gray-500" %>
			<%= form.date_field :due_date, class: "w-full md:w-auto px-3 py-2 shadow rounded-md border border-gray-200 outline-none mx-1" %>
			</div>
			<%= form.submit "Save", class: "w-1/2 btn py-2 bg-denim-600 text-white hover:bg-denim-700" %>
		</div>
	<% end %>
<% end %>

app/views/projects/_project.html.erb
<turbo-frame id="<%= dom_id project %>" class="flex flex-wrap justify-between items-center my-4 py-2 px-4 bg-denim-400/10 rounded-lg text-denim-900 shadow-md shadow-denim-200/50 border-b border-denim-100">
  <%= link_to project do %>
    <div class="flex flex-wrap items-center">
      <span class="font-semibold text-denim-800 w-full"><%= project.name %></span>
      <span class="text-denim-800 overflow-y-auto" style="max-height: 50px;"><%= project.description %></span>
    </div>
  <% end %>
  <div class="flex my-1 items-center">
    <%= link_to "Edit", edit_project_path(project),
                class: "btn bg-denim-800 text-white hover:bg-denim-900 text-sm"
    %>
    <div class="inline-block ml-1">
      <%= button_to "Delete", project_path(project),
                    method: :delete,
                    class: "btn bg-red-600/80 text-white hover:bg-red-600 text-sm",
                    data: { "turbo-frame": "_top" } %>
    </div>
  </div>
</turbo-frame>

app/views/projects/_projects.html.erb
<div id="projects" data-controller="checkbox">
	<%= render projects %>
</div>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.replace("notice", partial: "shared/flash") %>
<%= turbo_stream.update("projects_list", partial: "projects") %>

app/views/projects/edit.html.erb
<div>
  <turbo-frame id="<%= dom_id @project %>" class="flex flex-wrap justify-center">
    <%= render "form", task: @project %>
    <%= link_to "Nevermind", projects_path, class: "btn py-2 mx-auto my-2 w-1/2 bg-denim-800 hover:bg-denim-900 text-white flex justify-center" %>
  </turbo-frame>
</div>

app/views/projects/index.html.erb
<div class="grid justify-items-stretch">
	<div class="justify-self-center">
		<h1 class="font-bold text-2xl xl:text-3xl mb-4 text-center text-denim-900 "> <i class="fa-solid fa-diagram-project mr-2 text-xl lg:text-2xl"></i>projects</h1>

		<div class="flex flex-wrap w-full justify-center my-4">
			<div class="w-full md:w-3/4 lg:w-1/2 p-4 bg-gray-100/60 shadow-md rounded-lg">
				<%= render "form", project: @project %>
			</div>
		</div>

			<%= turbo_frame_tag "projects_list", class: "mt-4 flex justify-center mx-auto w-full md:w-3/4 lg:w-1/2" do %>
				<%= render "projects" %>
			<% end %>
		</div>

</div>

app/views/projects/show.html.erb
<%= turbo_frame_tag dom_id(@project) do %>
	<div class="w-full flex justify-between items-center p-6 text-denim-900 bg-white/80 shadow-md rounded-lg m-2">
		<div class="grid grid-cols-1 gap-2 w-full">
			<p><span class="font-semibold">Name:</span> <%= @project.name %></p>
			<p><span class="font-semibold">Description:</span> <%= @project.description.presence || "No Description Provided" %></p>
			<p><span class="font-semibold">Created by:</span> <%= @project.creator.email %></p>
		</div>
		<%= link_to projects_path, class: "text-sm ml-2 bg-denim-800 hover:bg-denim-900 text-white flex justify-center text-lg px-2 py-1 rounded-lg items-center" do %>
			Close <i class="fa-solid fa-xmark ml-1"></i>
		<% end %>
	</div>
<% end %>

app/views/projects/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@project)}" do %>
	<%= render @project %>
<% end %>
<%= turbo_stream.replace "notice", partial: "shared/flash" %>

app/views/shared/_flash.html.erb
<div id="notice" data-controller="flash">
  <% if notice.present? %>
    <div class="mx-auto md:w-2/3 w-full flex">
      <p class="mx-auto py-2 px-3 font-semibold bg-denim-800 border-denim-600 border-2 text-white rounded-lg inline-block">
      <% if notice.kind_of?(Array) %>
        <% notice.each do |e| %>
          - <%= e %><br />
        <% end %>
      <% else %>
        <%= notice %>
      <% end %>
      </p>
    </div>
  <% elsif flash.any? %>
    <% flash.each do |type, message| %>
      <div class="mx-auto md:w-2/3 w-full flex">
        <p class="mx-auto py-2 px-3 font-semibold bg-denim-800 border-denim-600 border-2 text-white rounded-lg inline-block">
          <%= message %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_toast.html.erb
<div class="flex justify-center">
 	<div id="toast-simple" class="<%= color if local_assigns[:color] %> backdrop-blur-xl mb-3 <%= "hidden" unless local_assigns[:visible] %> flex items-center max-w-xs p-4 space-x-4 text-white divide-x divide-gray-200 rounded-lg shadow space-x" role="alert">
			<div>
				<i class="<%= icon if local_assigns[:icon] %>" id="icon"></i>
			</div>
			<div class="pl-4 text-sm font-bold">
				<div id="message"><%= message if local_assigns[:message] %></div>
			</div>
	</div>
</div>

app/views/shared/_toast_icon_only.html.erb
<div class="flex justify-center">
 	<div data-controller="flash" id="toast-simple" class="<%= color if local_assigns[:color] %> backdrop-blur-xl flex items-center max-w-xs px-2 py-1 space-x-4 text-white divide-x divide-gray-200 rounded-full shadow space-x <%= classes if local_assigns[:classes] %>" role="alert">
			<div>
				<i class="<%= icon if local_assigns[:icon] %>" id="icon"></i>
			</div>	
	</div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, class: "flex w-full") do |form| %>
  <div class="w-full flex flex-wrap items-center">
    <%= form.text_field :name, placeholder: "Add new task", class: "flex-grow inline-block px-3 py-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-denim-600 text-white hover:bg-denim-700" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<turbo-frame id="<%= dom_id task %>" class="flex flex-wrap justify-between items-center my-4 py-2 px-4 bg-denim-400/10 rounded-lg text-denim-900 shadow-md shadow-denim-200/50 border-b border-denim-100">
  <%= form_with(model: task, class:"text-lg inline-block") do |form| %>
    <%= form.check_box :completed,
                      data: {
                        id: task.id,
                        type: "tasks",
                        action: "checkbox#toggle"
                      },
                      class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
  <% end %>
  <%= link_to task, class: "flex-grow mx-4" do %>
    <span class="font-semibold text-denim-800"><%= task.name %></span>
  <% end %>
  <div class="flex">
    <%= link_to "Edit", edit_task_path(task),
                class: "btn bg-denim-800 text-white hover:bg-denim-900 text-sm mr-1"
    %>
    <%= button_to "Delete", task_path(task),
                  method: :delete,
                  class: "btn bg-red-600/80 text-white hover:bg-red-600 text-sm",
                  data: { "turbo-frame": "_top" } %>
  </div>
</turbo-frame>

app/views/tasks/edit.html.erb
<turbo-frame id="<%= dom_id @task %>" class="flex flex-wrap justify-center">
  <%= render "form", task: @task %>
  <%= link_to "Nevermind", tasks_path, class: "btn py-2 mx-auto my-2 w-1/2 bg-denim-800 hover:bg-denim-900 text-white flex justify-center" %>
</turbo-frame>

app/views/tasks/index.html.erb
<div class="grid justify-items-stretch">
	<div class="justify-self-center">
		<h1 class="font-bold text-2xl xl:text-3xl mb-4 text-center text-denim-900"> <i class="fa-solid fa-list-check mr-2 text-xl lg:text-2xl"></i>tasks</h1>

		<div class="flex flex-wrap w-full justify-center my-4">
			<div class="w-full border-b-2 p-4 bg-gray-100/60 shadow-md rounded-lg">
				<%= render "form", task: @task %>
			</div>

			<div id="tasks" data-controller="checkbox" class="flex-grow mt-4">
				<div>
					<%= render tasks %>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/tasks/show.html.erb
<%= turbo_frame_tag dom_id(@task) do %>
	<div class="w-full flex justify-between items-center p-6 text-denim-900 bg-white/80 shadow-md rounded-lg m-2">
		<div class="grid grid-cols-2 gap-4 w-full">
			<p><span class="font-semibold">Description:</span> <%= @task.description %></p>
			<p><span class="font-semibold">Created by:</span> <%= @task.creator.email %></p>
		</div>
		<%= link_to tasks_path, class: "text-sm ml-2 bg-denim-800 hover:bg-denim-900 text-white flex justify-center text-lg px-2 py-1 rounded-lg items-center" do %>
			Close <i class="fa-solid fa-xmark ml-1"></i>
		<% end %>
	</div>
<% end %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@task)}" do %>
	<%= render @task %>
<% end %>
<%= turbo_stream.replace "notice", partial: "shared/flash" %>